# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.
version: '3.4'

networks:
    manage-users-net:

volumes:
    mssql-server-linux-data:

services: 
    manage-users-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: manage-users-api
        restart: always
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
            - manage-users-net
        deploy:
            restart_policy:
                condition: on-failure
                delay: 10s

    sql-server:
        image: mcr.microsoft.com/mssql/server
        container_name: sql-server
        environment:
            SA_PASSWORD: "DEV@12345"
            ACCEPT_EULA: "Y"
        volumes:
            - mssql-server-linux-data:/var/opt/mssql/data
        networks:
            - manage-users-net

